# This file configures the analyzer for the Culture Connection Flutter project

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disabled rules to reduce noise
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    use_key_in_widget_constructors: false
    avoid_print: false
    constant_identifier_names: false
    file_names: false
    library_private_types_in_public_api: false
    
    # Enabled best practices
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    directives_ordering: true
    package_api_docs: true
    prefer_single_quotes: true
    sort_constructors_first: true
    unawaited_futures: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning
