name: culture_connection
description: Culture Connection (Flutter)
publish_to: "none"  # remove if you plan to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Routing & state
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  
  # HTTP & API (for events only)
  http: ^1.2.2
  dio: ^5.7.0
  url_launcher: ^6.3.1
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # Date & Time
  intl: ^0.19.0
  
  # Image handling
  image: ^4.2.0
 
  
  # Environment
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/Loginimage1-2.png
    - assets/Loginimage1-3.png
    - assets/Tamearaimage.png
    - assets/Tamearaimage-3.png
    - assets/EventImage.png
    - assets/CC_PrimaryLogo_SilverPurple.png
    - assets/Startingimage7.png

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: Matches-StrikeRough
      fonts:
        - asset: assets/fonts/Matches-StrikeRough.otf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/Startingimage7.png
  android_12:
    image: assets/Startingimage7.png
