name: culture_connection
description: Culture Connection (Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.0
  riverpod_annotation: ^2.3.5
  
  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.0.0
  firebase_analytics: ^11.3.0
  cloud_functions: ^5.1.0
  
  # Navigation
  go_router: ^14.0.0
  
  # UI & Image Handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  flutter_svg: ^2.0.9
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Date & Time
  intl: ^0.19.0
  timeago: ^3.6.0
  table_calendar: ^3.0.9
  
  # Authentication & Social
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # UI Components
  flutter_slidable: ^3.0.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utilities
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  
  # Notifications
  flutter_local_notifications: ^16.2.0
  
  # Video
  video_player: ^2.8.1
  
  # Validation
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-VariableFont_slnt,wght.ttf
    - family: InterTight
      fonts:
        - asset: assets/InterTight-Italic-VariableFont_wght.ttf
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/Startingimage7.png
  android_12:
    image: assets/Startingimage7.png
