name: culture_connection
description: Culture Connection (Flutter)
publish_to: "none"
version: version: 2001.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  cloud_functions: ^5.1.3
  
  # Navigation
  go_router: ^14.2.7
  
  # UI & Image Handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  flutter_svg: ^2.0.10
  
  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Date & Time
  intl: ^0.19.0
  timeago: ^3.6.0
  table_calendar: ^3.0.9
  add_2_calendar: ^3.0.1
  
  # Authentication & Social
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utilities
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  share_plus: ^10.0.3
  file_picker: ^8.1.4
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Video
  video_player: ^2.8.1
  
  # Validation
  email_validator: ^2.1.17
  
  # Image handling
  image: ^4.2.0
  
  # Environment
  flutter_dotenv: ^5.1.0
  
  # In-App Purchases
  in_app_purchase: ^3.1.11
  purchases_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/Loginimage1-2.png
    - assets/Loginimage1-3.png
    - assets/Tamearaimage.png
    - assets/Tamearaimage-3.png
    - assets/EventImage.png
    - assets/CC_PrimaryLogo_SilverPurple.png
    - assets/Startingimage7.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Italic-VariableFont_wght.ttf
          style: italic
    - family: Matches-StrikeRough
      fonts:
        - asset: assets/fonts/Matches-StrikeRough.otf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/Startingimage7.png
  android_12:
    image: assets/Startingimage7.png